name: "Trivy"
author: "Cloudfy9"
description: "GitHub action to scan docker images for vulnerability issues using trivy."
inputs:
  image_name:
    description: "This input contains the docker images to scan"
    required: true
  scan_type:
    description: "This input contains the scan type e.g. image, repository etc..."
    required: false
    default: "image"
  format:
    description: "This input contains the scan output format e.g. table or json"
    required: false
    default: "table"
  severity:
    description: "This input contains the comma separated list of severities e.g. UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    required: false
  exit_code:
    description: "This input contains the exit code in case vulnerabilies found"
    required: false
    default: "128"
  vuln_type:
    description: "This input contains the vulnerability types to scan for"
    required: false
    default: "os,library"
branding:
  icon: "camera"
  color: "red"

runs:
  using: 'docker'
  image: 'Dockerfile'
